# .github/workflows/e2e.yml
# test the deployed Netlify site
name: e2e
on:
  workflow_dispatch:
    inputs:
      siteName:
        description: Netlify Site Name
        required: false
      deployPrimeUrl:
        description: Deployed URL
        required: true
jobs:
  show-event:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Testing url ${{ github.event.inputs.deployPrimeUrl }}"
      - run: echo "Site name ${{ github.event.inputs.siteName }}"
